default : decision_tree random_forest
decision_tree : decision_tree.cpp decision_tree.h
	g++ decision_tree.cpp -o decision_tree  
random_forest : random_forest.cpp random_forest.h
	g++ random_forest.cpp -o random_forest  
